stores:
  yaml:
    indent: 2

keys:
  age: &age_keys >-
    age13n7alswx94tulmsefa59jrzeuynd49q4jcerdhypy52x6pc53ups28uzn7

creation_rules:
  - path_regex: "secret_.*"
    age: *age_keys
  - path_regex: ".*\\.tfstate"
    age: *age_keys
