{
 "title": "Resource Usage",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "apps",
    "query": {
     "query": "label_values(pod_origin,origin_app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mCPU" } },
   "targets": [
    {
     "expr": "sum by (origin_app) (\n  rate(container_cpu_usage_seconds_total{container!=\"\", pod!=\"\"}[$__rate_interval])\n  * on(pod, namespace) group_left(origin_app)\n  pod_origin\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (origin_app) (\n  container_memory_working_set_bytes{container!=\"\", pod!=\"\"}\n  * on(pod, namespace) group_left(origin_app)\n  pod_origin\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage: $apps ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mCPU" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  rate(container_cpu_usage_seconds_total{container!=\"\", pod!=\"\"}[$__rate_interval])\n  * on (namespace, pod) group_left(origin_app)\n  pod_origin{origin_app=~\"$apps\"}\n) * 1000",
     "legendFormat": "{{namespace}}: {{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage: $apps ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  container_memory_working_set_bytes{container!=\"\", pod!=\"\"}\n  * on (namespace, pod) group_left(origin_app)\n  pod_origin{origin_app=~\"$apps\"}\n)",
     "legendFormat": "{{namespace}}: {{pod}}"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (origin_app) (\n  (\n    increase(container_fs_reads_bytes_total{container!=\"\"}[$__rate_interval]) \n  )\n  * on(pod, namespace) group_left(origin_app)\n  pod_origin\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (origin_app) (\n  (\n    increase(container_fs_writes_bytes_total{container!=\"\"}[$__rate_interval])\n  )\n  * on(pod, namespace) group_left(origin_app)\n  pod_origin\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Ingress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (origin_app) (\n  (\n    increase(container_network_receive_bytes_total[$__rate_interval])\n  )\n  * on(pod, namespace) group_left(origin_app)\n  pod_origin\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Egress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (origin_app) (\n  (\n    increase(container_network_transmit_bytes_total[$__rate_interval])\n  )\n  * on(pod, namespace) group_left(origin_app)\n  pod_origin\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}