apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  # Necessary to use Gateway routing
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#prerequisites
  server.insecure: "true"
